MercedesBlog/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'posts#index'
  resources :posts
  resources :image, only: [:create, :destroy]
  resources :tags, only: [:show]

end

MercedesBlog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MercedesBlog/app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
end

MercedesBlog/app/models/post.rb
class Post < ApplicationRecord

  mount_uploader :image, ImageUploader
  validates :title, :summary, :body, presence: true
  has_many :taggings, :dependent => :destroy
  has_many :tags, through: :taggings

  def all_tags
    self.tags.map(&:name).join(', ')
  end

  def all_tags=(names)
    self.tags = names.split(', ').map do |name|
      Tag.where(name: name.strip).first_or_create
    end
  end

end

MercedesBlog/app/models/tag.rb
class Tag < ApplicationRecord

  has_many :taggings
  has_many :posts, through: :taggings

  def self.counts
    self.select("name, count(taggings.tag_id) as count").joins(:taggings).group("name, taggings.tag_id")
  end

end

MercedesBlog/app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

MercedesBlog/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable,:confirmable, :validatable
end

MercedesBlog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  add_flash_types :success, :danger, :info, :warning
end

MercedesBlog/app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def create
    @picture = Picture.new(image_params)
    @picture.save
    respond_to do |format|
      format.json { render :json => { url: @picture.image.url(:large), picture_id: @picture.id } }
    end
  end

  def destroy
    picture = Picture.find(params[:id])
    picture.destroy
    respond_to do |format|
      format.json { render json: { status: :ok } }
    end
  end

  private

  def image_params
    params.require(:picture).permit(:image)
  end
end

MercedesBlog/app/controllers/posts_controller.rb
class PostsController<ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:show]

  def index
    @posts = Post.order(:id).page params[:page]
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, success: 'Successfuly created'
    else
      flash.now[:danger] = 'Article has not been created`'
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update_attributes(post_params)
      redirect_to @post, success: 'Successfuly updated '
    else
      render :edit, danger: 'Article hasn`t been updated'
    end
  end

  def destroy
    @status = Post.find(params[:id])
    if @status.present?
      @status.destroy
    end
    redirect_to posts_path, success: 'Succesfuly deleted'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :summary, :body, :image, :all_tags)
  end

end

MercedesBlog/app/controllers/tags_controller.rb
class TagsController<ApplicationController
  def show
    @tag = Tag.find_by(name: params[:id])
    @posts = @tag.posts
  end
end

MercedesBlog/app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for(name)
    {
        success: "alert-succes",
        error: "alert-danger",
        alert: "alert-warning",
        danger: "alert-danger",
        notice: "alert-info",
    }[name.to_sym] || name
  end
end

MercedesBlog/app/helpers/posts_helper.rb
module PostsHelper
  def tag_cloud(tags, classes)
    max = tags.sort_by(&:count).last
    tags.each do |tag|
      index = tag.count.to_f / max.count * (classes.size-1)
      yield(tag, classes[index.round])
    end
  end
end

MercedesBlog/app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

MercedesBlog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MercedesBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div class="card mt-1">
    <div class="container d-flex">
    <div class="nav">
      <a class="navbar-brand">
        <%= image_tag "/assets/mblogo.svg", height: '30', width: '30'%>
        Mercedes-Benz Blog
      </a>
      <ul class="nav nav-tabs mr-2">

          <li class="nav-item ml-2 mr-2">
            <%= link_to 'All articles', root_path, class:'btn btn-primary'%>
          </li>
          <li class="nav-item ml-2 mr-2">
            <%= link_to 'New article', new_post_path, class:'btn btn-primary'%>
          </li>
      </ul>
        <ul class="nav nav-tabs justify-content-end">
          <% if user_signed_in?  %>
                <li class="nav-item ml-2 mr-2">
                  <%= link_to 'Logout', destroy_user_session_path, method: :delete, class:'btn btn-primary' %>
                </li>
                <%else %>
                  <li class="nav-item ml-2 mr-2">
                    <%= link_to 'Login', new_user_session_path, class:'btn btn-primary'%>
                  </li>
                  <li class="nav-item ml-2 mr-2">
                    <%= link_to 'Registration', new_user_registration_path, class:'btn btn-primary' %>
                  </li>
            <% end %>
        </ul>

      <div class="container main">
        <div class="row">
          <div class="col-md-12">
           <% flash.each do |name, message| %>
              <div class="alert <%= bootstrap_class_for(name)%>">
                <button class="close" data-dismiss="alert">&times;</button>
                <%= message %>
              </div>
            <% end %>
          </div>
      </div>
    </div>

    <div class="container mt-3 mb-5">
        <div class="row">
          <div class =" col-10">
            <%= yield %>
            </div>
              <div class="col-2 ">
                <small>
                <% tag_cloud(Tag.counts, %w{tag1 tag2 tag3 tag4 tag5}) do |tag, css_class| %>
                 <%= link_to tag.name, tag_path(tag.name), class: css_class %>
                <% end %>
                </small>
              </div>

            </div>
        </div>
      </div>
    </div>
  </div>

</html>

MercedesBlog/app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

    /**
     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

    var disqus_config = function () {
    this.page.url = 'http://localhost.com<%= request.original_fullpath %>';  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = '<%= @post.id %>' // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };

    (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://MercedesBlog.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>

MercedesBlog/app/views/posts/_form.html.erb
<% if @post && @post.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
        <%end %>
    </ul>
  </div>
<%end %>

<%=form_for @post, html: {multipart: true} do |f| %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class:'form-control'%>
  </div>

  <div class="form-group">
    <%= f.label :summary %>
    <%= f.text_field :summary, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= f.trix_editor :body , class: 'editor'%>
    </div>

  <div class="form-group">
    <%= f.label :all_tags  %>
    <%= f.text_field :all_tags , class: 'form-control'%>
  </div>

  <div class="form-group">
    <%= f.submit 'Create', class:'btn btn-primary' %>
  </div>
<% end %>

MercedesBlog/app/views/posts/_post.html.erb
<article class="post">
  <section class="post-head mt-2 mb-2 text-justify">
    <h2 class="card-title"><%= link_to post.title, post_path(post) %></h2>
    <small> <%= post.created_at.to_date.strftime("%d %B, %Y")%></small>
    |
    <%= link_to 'Change', edit_post_path(post) %>
    <%= link_to 'Delete', post_path(post), method: :delete, data: {confirm: 'Are you sure?'} %>
  </section>

  <section class="post-summary">
<%= post.summary %>
  </section>

  <section class="footer-summary">
    <%= raw post.tags.map(&:name).map { |t| link_to t, tag_path(t), class:'badge badge-pill badge-primary'}.join(' ')%>
  </section>
</article>

MercedesBlog/app/views/posts/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

MercedesBlog/app/views/posts/index.html.erb
<h1>Posts</h1>

<%= render @posts %>
<div class="mt-3 mb-3">
<%= paginate @posts%>
</div>

MercedesBlog/app/views/posts/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

MercedesBlog/app/views/posts/show.html.erb
<article class="post">
  <section class="post-head mt-2 mb-2">
    <h1 class="card-title"><%= @post.title %></h1>
    <small> <%= @post.created_at.to_date.strftime("%d %B, %Y")%></small>
    |
    <%= link_to 'Change', edit_post_path(@post) %>
    <%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: 'Are you sure?'} %>
  </section>

  <section class="post-body mt-3 mb-2 pt-1 text-justify">
    <p><%= @post.body.html_safe %></p>
  </section>
</article>

<%= render 'disqus' %>

MercedesBlog/app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>
<% if @tag.posts.empty? %>
<h2>Article not found</h2>
<% else %>
<%= render @tag.posts %>
<% end %>